language: node_js
node_js:
  - '10.13'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - echo 'Test starts!!!'
  #- npm run build
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - echo 'Build starts!!!'
  - npm run-script build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "s3://dmvfootballheadz.com"
  region: $AWS_DEFAULT_REGION
  skip_cleanup: true
  local_dir: dist/footballheadzUI
  on:
    branch: develop