language: node_js
node_js:
  - '10.13'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: test
      script:
        - echo 'Start Testing'
        - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
    - stage: deploy
      script:
        - ng build && npm run aws-deploy

stages: 
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to develop
    if: type = push AND branch = develop